### ISSUE TITLE
Multi line operations involving the pop up menu helper does not work as intended and needs fixing

### ISSUE THREAD

**Issue by TwistTheNeil** [borisv13/GitHub-Flavored-Markdown-Eclipse-Plugin#184]
How to reproduce (based on master)

1. Select some multi-line text like:
```
This

Is

A

Test
```
2. ctrl+space
3. select block quote or code blocks
4. Notice that the attribute is only applied to the first line.

**Comment by aw3227** [comment]
Updated code for blockquote and added same functionality to ordered and unordered list. pull request pending

**Comment by aw3227** [comment]
merged into master
