### ISSUE TITLE
OrderedList test is wrong

### ISSUE THREAD

**Issue by TwistTheNeil** [borisv13/GitHub-Flavored-Markdown-Eclipse-Plugin#186]
addOrderedList test is wrong.

```
		String actual = addStuffToString.orderedList("word\nword\n");
		assertEquals("1.  word\n1.  word\n", actual);
```

I believe it should be`1. word\n2.word`.

Please check the GFM guide: https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf

**Comment by aw3227** [comment]
This test is actually correct. GFM allows you to create an ordered list by adding "1. " to the front of every row. It can also be done the way that you suggested but it is much more difficult to implement a function that does that so we went with just 1's. the list below is made with "1. " in front of each row.
you can also duplicate it on dillinger and see this guide:
https://guides.github.com/features/mastering-markdown/

1. one
1. two
1. three
